POST http://localhost:8080/create_account HTTP/1.1
Content-Type: application/json

{
  "username": "admin@gmail.com",
  "password": "Nyc#1234",
  "first_name": "Admin",
  "last_name": "User",
  "city": "New York",
  "state": "NY"
}

