
Get http://localhost:8080/api/trail

}

###
Get http://localhost:8080/api/trail/2

}

###Trail Add
POST http://localhost:8080/api/trail
Content-Type: application/json

{
    
    "name":"TestName",
    "city":"Austin",
    "state":"TX",
    "trailLenght": "6",
    "rating": "M",
    "trailMap": "",
    "description": "",
    "appUserId": "2"
}

###Trail Update
PUT http://localhost:8080/api/trail/3
Content-Type: application/json

{
    "trailId":"3",
     "name":"TestNameUpdated",
    "city":"Austin",
    "state":"TX",
    "trailLenght": "6",
    "rating": "M",
    "trailMap": "",
    "description": "tt",
    "appUserId": "2"
   
}

###Delete Trail
Delete http://localhost:8080/api/trail/3
